"""empty message

Revision ID: 20998baa3cbc
Revises: 3a24be786b3f
Create Date: 2022-04-11 17:04:50.445457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20998baa3cbc'
down_revision = '3a24be786b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_stripe_payment_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_stripe_payment_id')
    # ### end Alembic commands ###
