"""empty message

Revision ID: 40a92f7d0f47
Revises: 6c5b98761104
Create Date: 2022-06-28 16:05:24.517729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a92f7d0f47'
down_revision = '6c5b98761104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_statistics', sa.Column('new_subs_lifetime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_statistics', 'new_subs_lifetime')
    # ### end Alembic commands ###
