"""empty message

Revision ID: bc350dbb9fcb
Revises: 40a92f7d0f47
Create Date: 2022-06-30 14:39:24.702527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc350dbb9fcb'
down_revision = '40a92f7d0f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_statistics', sa.Column('month_gross_usd', sa.Integer(), nullable=True))
    op.add_column('subscription_statistics', sa.Column('year_gross_usd', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_statistics', 'year_gross_usd')
    op.drop_column('subscription_statistics', 'month_gross_usd')
    # ### end Alembic commands ###
